# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190513_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator_sm',
            field=models.ImageField(default='avator/girls_02.jpg.50x50_q85_crop.jpg', upload_to='avator/%Y%m%d/', verbose_name='头像缩略图'),
        ),
    ]
