# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_findpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findpassword',
            name='creat_time',
            field=models.DateTimeField(auto_now=True, verbose_name='重置时间'),
        ),
    ]
