# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190516_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findpassword',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
    ]
